#!/bin/bash 
#Copyright (C) 2015 nowardev nowardev@gmail.com
 
#This file is part of kde-peace-settings.
 
#kde-peace-settings is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.




bin="/usr/local/bin/"
folder_local_bash_scripts="$HOME/bin"
local_user_outfolder="$(kf5-config --path services | cut -d: -f1)"
local_system_outfolder="$(kf5-config --path services | cut -d: -f2)"

system_outfolder="$(kf5-config --path services | cut -d: -f3)"
#remove /local form /usr/local/share/applications


local_system_application_folder="$(qtpaths --paths ApplicationsLocation | cut -d: -f3)"
local_user_application_folder="$( qtpaths --paths ApplicationsLocation | cut -d: -f1)"
system_application_folder="${local_system_application_folder/\/local/}"

if [[ $(type plasmashell ) ]] ; then refreshcommand="kbuildsycoca5"; elif [[ $(type plasma-desktop) ]]; then refreshcommand="kbuildsycoca4" ; else refreshcommand="" && echo $"no plasma installation detected!!"; fi 


prefix="$(kde4-config --prefix)"
localprefix="$(kde4-config --localprefix)"


echo "
PARAMETERS:

USER BIN folder for script......................$folder_local_bash_scripts
USER outfolder service menu.....................$local_user_outfolder
USER application menu entry location............$local_user_application_folder 


SYSTEM BIN folder for script....................$bin
SYSTEM LOCAL out folder service menu............$local_system_outfolder
SYSTEM outfolder service menu...................$system_outfolder
 
SYSTEM application menu entry...................$system_application_folder
SYSTEM LOCAL application menu entry.............$local_system_application_folder

"


#import extra function from other files if they exit 
if [[ -e "$PWD/extra_bash_function_installation" ]]; then 
	echo $"Extra installation file detected loading functions
. $PWD/extra_bash_function_installation"

. "$PWD/extra_bash_function_installation"  
fi 

if [[ -e "$PWD/extra_bash_function_deinstallation" ]]; then 
	echo $"Extra deinstallation file detected loading functions
. $PWD/extra_bash_function_deinstallation"

. "$PWD/extra_bash_function_deinstallation" 
fi 
 


function_check_folder_and_create_it_if_doesnt_exist () {
	if [[ ! -d "$1" ]]; then 
		echo $"..............Folder $1  doen't exist...creating  mkdir $1
		"
		
		mkdir "$1"
	else
		echo $"..............Folder $1 exist 
		"
	fi 
	
	
}

function_checksudo(){

if [[ $sudoerror == true ]] ; then
function_system
wrongpas=$"before you typed a WRONG PASS"
fi

}

function_system() {

	sudoerror=false
	pas=$(kdialog --password $"Insert Root Password $wrongpas" 2>/dev/null )
	
	
	if [[ -z "$pas" ]];then
		kdialog --error $"No password given exiting..." 2>/dev/null 
		exit  
	fi
		
		
		#install every script with the correct permission
		directory="$PWD/usr/bin/"
		if [[  -d "$directory"  ]] ; then
			for file in $PWD/usr/bin/* ; do
				echo "installing..... sudo -S  install -m 755 -D "$file"  "/usr/local/bin""
				echo "$pas" | sudo -S  install -m 755 -D "$file"  "/usr/local/bin" 2>/dev/null 
				
				#wtf need to fix this shit very ugly xD
				if [[ $? ==  1 ]]; then
					sudoerror=true
				else 
					sudoerror=false
				fi
			done
		else
			echo "directory $directory  doens't exit  skipping"
		fi 
							
							
							
	function_checksudo


#install the service menu 
	directory="$PWD"$system_outfolder""
	if [[  -d "$directory"  ]] ; then 
		for file in "$directory"*.desktop;  do
			echo "installing..... sudo -S install -m 644 -D "$file"  "$local_system_application_folder""
			echo "$pas" | sudo -S install -m 644 -D "$file"  "$local_system_application_folder" 
		done
	else
		echo "directory $directory doesn't exit skipping "
	fi
#install menu entry 

	directory="$PWD/usr/share/applications/kde4/"
	if [[  -d "$directory"  ]] ; then 
# 		if [[ -d "$PWD/usr/share/applications/kde4/" ]]; then 
			echo " folder application entry detected $PWD/usr/share/applications/kde4/"
			
			for file in $PWD/usr/share/applications/kde4/*.desktop ; do 
				echo "installing..... sudo -S install -m 755 -D "$file"  "$local_system_application_folder""
				echo "$pas" | sudo -S install -m 755 -D "$file"  "$local_system_application_folder" 
			done 
# 				
# 		fi 
	else
		echo "directory $directory doesn't exit skipping "
	fi 

# echo  "running .....$refreshcommand  update service menus... wait.."
echo 
echo 
 $refreshcommand 2>/tmp/servicemenubashinstaller.log  # echo "$pas" | sudo -S -u $SUDO_USER #GET  $refreshcommand running like normal user ..to avoid error message
echo
echo $"END! EVERYTHING DONE!"
kdialog --passivepopup $"$PWD Service Menu Installed.. bye" 2 2>/dev/null
 
#reset password 
pas=""

if [[ -e "$PWD/extra_bash_function_installation" ]]; then 
	if [[ $(declare -F function_extra_install_global ) ]]; then 
		echo $"Function Extra Install Global"
		function_extra_install_global	
	else 
		echo $"No Extra global Install functions"
	fi 
	
	if [[ $(declare -F function_extra_install_system )  ]]; then 
		echo "Function Extra Install System executing.."
		function_extra_install_system
	else 
		echo $"No Extra wide Install functions"
	fi 

fi 
}

 

function_local(){

#create a folder to put script and set it to be recognized by the system at every login 
function_check_folder_and_create_it_if_doesnt_exist "$folder_local_bash_scripts"

# if  [[ ! -d "$folder_local_bash_scripts"  ]] ; then
# echo "mkdir "$folder_local_bash_scripts""
# mkdir "$folder_local_bash_scripts"
# fi

#if the variable is NOT EMPTY then don't do again export 
if  [[ $PATH != *"$folder_local_bash_scripts"* ]]; then
# 	export "PATH=$PATH:$folder_local_bash_scripts"
	 
	#execute the command everytiem you login
	kdialog --title $"INFO"  --yes-label $"Yes, i want Add"  --no-label $"Noo" --cancel-label $"Cancell"  --warningyesnocancel   $" I have detected that in your \$PATH there is not this folder $HOME/bin , so you will not be able to execute this script the program locally , DO YOU WANT ADD $HOME/bin to your path?" 
	
	if [[ $? == 0 ]] ; then 
		echo "export PATH=$PATH" >> "$HOME/.bashrc" 
		#load the new stuff into bash shell 
		source "$HOME/.bash_profile"
	else
		kdialog --title $"Service Menu Installer"  --msgbox  $" This Program is installed locally but you will not be able to run it properly: this is your current $PATH , and should be $PATH:$folder_local_bash_scripts"
  
	fi 
	 


else
	echo
	echo $"..............$folder_local_bash_scripts already on path ...skipping"
	echo
fi 


 


#install every script with the correct permission
	if [[ -d "$PWD/usr/bin/" ]]; then 
		for file in $PWD/usr/bin/* ; do
			echo "..............install -m 755 -D "$file"  "$folder_local_bash_scripts""
			install -m 755 -D "$file"  "$folder_local_bash_scripts" 
		done
	fi 

#install the service menu 
	if [[ -d "$PWD"$system_outfolder"ServiceMenus/" ]]; then 
		for file in $PWD/usr/share/kde4/services/ServiceMenus/*.desktop ;  do
			echo "installing.....install -m 644 -D "$file"  "$local_user_outfolder""
			install -m 644 -D "$file"  "$local_user_outfolder" 
		done
	fi 
#install the menu entry if exist 

  #install menu entry in ~/.local/share/applications/
	if [[ -d "$PWD/usr/share/applications/kde4/" ]]; then 
		function_check_folder_and_create_it_if_doesnt_exist "$local_user_application_folder"
		
	
		for file in $PWD/usr/share/applications/kde4/*.desktop ; do 
 			echo "installing.....install -m 755 -D $file "$local_user_application_folder"" 
			install -m 755 -D "$file"  "$local_user_application_folder"
		done
	fi 

	$refreshcommand 2>/tmp/servicemenubashinstaller.log

	kdialog --passivepopup $"$PWD Service Menu Installed.. bye" 2 2>/dev/null
	kdialog --msgbox $"if you can't launch the program Please login and logout , this should load the new bash_profile" 2>/dev/null
	
	if [[ -e "$PWD/extra_bash_function_installation" ]]; then 
		if [[  $(declare -F function_extra_install_global )  ]]; then
			echo "Global Extra function Detected Executing.."
			function_extra_install_global
		else 
			echo $"No Extra global Install functions"
		fi
			
		if [[ $(declare -F function_extra_install_local ) ]]; then 
			echo "Function Extra Install Local executing.."
			function_extra_install_local
		else 
			echo $"No Extra Local Install functions"
		fi 

	fi 
 
}


function_remove_local(){

##remove local 
messageremoved=""
#remove every script 
 for file in $PWD/usr/bin/* ; do
 file="${file##*/}" 
#  file="${file%%.*}"
 	if [[ -e "$folder_local_bash_scripts/$file"  ]]; then 
 	echo "rm   "$folder_local_bash_scripts/$file""
	rm   "$folder_local_bash_scripts/$file" 
	messageremoved="$messageremoved $folder_local_bash_scripts/$file"
	else 
	echo $"$folder_local_bash_scripts/$file file doesn't exit"
	fi
 
  
  done

#remove the service menu 
  
   for file in "$PWD"$local_user_outfolder"ServiceMenus/"*.desktop ;  do
 file="${file##*/}" 
#  file="${file%%.*}"
#  	if [[ -e ""$localprefix"/share/kde4/services/ServiceMenus/"$file""  ]]; then 
		echo "rm  "$local_user_outfolder"ServiceMenus/$file"
		rm  ""$local_user_outfolder"ServiceMenus/$file" 
		messageremoved="$messageremoved  "$local_user_outfolder"ServiceMenus/$file"
# 	else 
# 		echo $" ""$localprefix"share/kde4/services/ServiceMenus/$file"  file does not exit... skipping"
# 	fi
 
  done
  
 
 
#remove menu entry
  #install menu entry in ~/.kde/share/applnk
	if [[ -d "$PWD/usr/share/applications/kde4/" ]]; then 
		for file in $PWD/usr/share/applications/kde4/*.desktop ; do
			file="${file##*/}"
 			echo "removing ... $local_user_application_folder/$file" 
			rm  "$local_user_application_folder/$file"
			messageremoved="$messageremoved  "$local_user_application_folder"/$file "
		done
	fi 

####################################################################
$refreshcommand 2>/tmp/servicemenubashinstaller.log
kdialog --passivepopup $"Removed these files  $messageremoved" 2 2>/dev/null

if [[ -e "$PWD/extra_bash_function_deinstallation" ]]; then 
	
	if [[ $(declare -F function_extra_deinstall_global )  ]]; then 
		echo $"Function Extra Deinstall Global Local detected executing .."
		function_extra_deinstall_global
	else
		echo  $"No Function Extra Global Local Deinstall Detected"
	fi 
	
	if [[ $(declare -F function_extra_deinstall_local )   ]]; then 
		echo "Function Extra Deinstall Local executing.."
		function_extra_deinstall_local
	else 
		echo $"No Function Extra Local Deinstall Detected"
	fi 

fi 


}
 
function_remove_system(){


messageremoved=""
sudoerror=false
pas=$(kdialog --password $"Insert Root Password $wrongpas" 2>/dev/null)


if [[ -z "$pas" ]];then
kdialog --error $"No password give exiting..." 2>/dev/null
exit  
fi

################remove systemwide

for file in $PWD/usr/bin/*; do
file="${file##*/}" 
# file="${file%%.*}"
 
	if [[ -e "/usr/local/bin/$file"  ]]; then
	echo $"rm   "/usr/local/bin/$file""
	echo "$pas" | sudo -S rm   "/usr/local/bin/$file" 
	messageremoved="$messageremoved /usr/local/bin/$file"
	else 
	echo $""/usr/local/bin/$file" file doesn't exit"
	fi
done

#remove the service menu 

for file in "$PWD"$local_user_outfolder"ServiceMenus/"*.desktop ;  do
file="${file##*/}" 
# file="${file%%.*}"
 
	if [[ -e ""$local_user_outfolder"ServiceMenus/"$file""  ]]; then 
	echo "rm   $prefix/share/kde4/services/ServiceMenus/$file"
	echo "$pas" | sudo -S rm  ""$local_user_outfolder"ServiceMenus/"$file"" 
	messageremoved="$messageremoved ""$local_user_outfolder"ServiceMenus/$file""
	else 
	echo $""$local_user_outfolder"ServiceMenus/"$file" file doesn't exit"
	fi
done

#remove the menu entry if it exist
if [[ -d "$PWD/usr/share/applications/kde4/" ]]; then 
	echo $"Folder Menu entry detected"
	for file in $PWD/usr/share/applications/kde4/*.desktop ; do 
		file="${file##*/}"
		if [[ -e ""$local_system_application_folder"/$file"  ]]; then 
			echo "rm   "$local_system_application_folder"/$file"
			echo "$pas" | sudo -S rm  ""$local_system_application_folder"/$file"
			messageremoved="$messageremoved "$local_system_application_folder"/$file"
		fi 
	done
			
fi 
			
$refreshcommand 2>/tmp/servicemenubashinstaller.log
kdialog --passivepopup $"Removed these files  $messageremoved" 2>/dev/null
  
if [[ -e "$PWD/extra_bash_function_deinstallation" ]]; then 
	
	if [[ $(declare -F function_extra_deinstall_global )  ]]; then 
		echo $"Function extra deinstall global detected executing"
		function_extra_deinstall_global
	else
		echo  $"No Function Extra Global System Deinstall Detected"
	fi 
	
	if [[ $(declare -F function_extra_deinstall_system ) ]]; then 
		echo $"Function Extra Deinstall System  detected executing"
		function_extra_deinstall_system
	else
		echo $"No Function Extra Deinstall System detected"
	fi 

fi 
}

function_main(){
 
answer=$(kdialog  --title $"Service menu installation menu " --menu  $"Installation Menu: choose an installation option"  l  $"Local Installation"  sw $"System  Installation" neutral "**********************************************" r $"Remove Service Menu Locally" rs $"Remove Service Menu from the System" --default "Local Installation" 2>/dev/null)
echo "menu entry $answer"
case $answer in 

l)
function_local 

;;

sw)
function_system

;;

r)
function_remove_local
;;
rs)
function_remove_system
;;
neutral)
function_main
;;
*)
#kdialog --passivepopup $":P no option so... installation aborted" 2
exit 0
;;
esac
}






function_main
