#!/bin/bash -x

#
#Copyright (C) 2012 nowardev nowardev@gmail.com
 
#This file is part of kde-peace-settings.
 
#kde-peace-settings is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.



function_install(){ 

for file in  "$PWD"/bin/* ; do 

cp "$file" /usr/bin/${file##*/}       #joke ! xD
sudo chmod +x /usr/bin/${file##*/}
done 

for file in  "$PWD"/etc/X11/Xsession.d/* ; do 

cp "$file" /etc/X11/Xsession.d    
 
done 


#mime 
for file in  "$PWD"/usr/share/applications/* ; do 

cp "$file" /usr/share/applications  
 
done 

#fonts

for file in "$PWD"/etc/fonts/conf.avail/*.conf ; do
cp "$file"   /etc/fonts/conf.avail/
done
#fontconfig
for file in "$PWD"/usr/share/fontconfig/conf.avail/*.conf ; do
cp "$file"   /usr/share/fontconfig/conf.avail/
done
cp -r "$PWD"/usr/share/fonts/cantarell  /usr/share/fonts/  
cp -r  "$PWD"/usr/share/fonts/opentype/cantarell /usr/share/fonts/opentype/






#bug
for folder in "$PWD"/usr/share/bug/*/ ; do 
cp -r "$folder" /usr/share/bug/
done

#doc

for folder in "$PWD"/usr/share/doc/*/ ; do 
cp -r "$folder" /usr/share/doc/
done



for file in "$PWD"/etc/fonts/conf.avail/*.conf ; do
cp "$file"   /etc/fonts/conf.avail/
done



#kde peace settings

cp -r  "$PWD"/usr/share/kde-peace-settings  /usr/share/

#kde peace doc 
cp -r  "$PWD"/usr/share/doc/kde-peace-settings  /usr/share/doc/
}

function_uninstall(){

rm -R  /usr/share/doc/kde-peace-settings
rm -R  /usr/share/kde-peace-settings  
rm /usr/share/applications/mimeapps.list
rm /etc/X11/Xsession.d/50peace



for file in   /usr/bin/ktexeditor-open-folder /usr/bin/lprinter-qt  /usr/bin/lprinter-qt-office  /usr/bin/vservice ; do 
rm "$file"
done 
}



if [ "$(id -u)" = 0 ]; then 
	echo "you have the power lol" 
	echo "installing..."
else 
	echo "YOU ARE NOT ROOT TO INSTALL  YOU MUST BE ROOT. "
	echo "have you typed wrong password?"
	exit 0
fi

echo "Do you want install or unistall  (i\u)"
read
case $REPLY in
[i/I][n/N][s/S][t/T][a/A][l/L][l/L]|[i/I]) 



function_install


;;
 
[u/U][n/N][s/S][t/T][a/A][l/L][l/L]|[u/U])
function_uninstall
;;

*)
echo "dude u to unistall i to install"
exit
;;
esac

