#!/bin/bash
#Copyright (C) 2013 nowardev nowardev@gmail.com
 
#This file is part of kde-peace-settings.
 
#kde-peace-settings is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#



if [[  -z  "$1"    ]] ; then
echo "no key exiting.."
exit
 
fi 

if [[ "$1" =~ \* ]]; then 

b=($(pacman -qSl | grep -i ${1//\*/}| grep -v l10n )) 
if [[ -z "${b[@]}" ]]; then
echo $"not packages found with $1 name"
exit
else 

echo $"
Packages selected: 

${b[@]} 

do you want install these packages ? Y\n or press ENTER for YES"
read   


case "$REPLY" in

""|[yY]|-y|-Y]|[yY][eE][sS])
sudo pacman -Syu "${b[@]}"

;;

[nN]|[nN][oO])
exit

;;
*)
echo $"type yes or no ... exiting"
exit 
esac

REPLY=""
fi 
fi 
  
