#!/bin/bash -x

#
#Copyright (C) 2012 nowardev nowardev@gmail.com
 
#This file is part of kde-peace-settings.
 
#kde-peace-settings is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.



function_install(){ 

echo "

install -m 755 -D peace-debian-install /usr/bin
cp aptk.desktop  /usr/share/applications/kde4/
cp aptk-service.desktop /usr/share/kde4/services/ServiceMenus/

"
cd  "$PWD"/Aptk/ 

cp  peace-debian-installer /usr/bin
chmod 755 /usr/bin/peace-debian-installer
cp aptk.desktop  /usr/share/applications/kde4/
cp aptk-service.desktop /usr/share/kde4/services/ServiceMenus/

}

function_uninstall(){


echo "
rm /usr/bin/peace-debian-install
rm /usr/share/applications/kde4/aptk.desktop
rm /usr/share/kde4/services/ServiceMenus/ptk-service.desktop
"
 
rm /usr/bin/peace-debian-install
rm /usr/share/applications/kde4/aptk.desktop
rm /usr/share/kde4/services/ServiceMenus/ptk-service.desktop

}



if [ "$(id -u)" = 0 ]; then 
	echo "you have the power lol" 
	echo "installing..."
else 
	echo "YOU ARE NOT ROOT TO INSTALL  YOU MUST BE ROOT. "
	echo "have you typed wrong password?"
	exit 0
fi

echo "Do you want install or unistall  (i\u)"
read
case $REPLY in
[i/I][n/N][s/S][t/T][a/A][l/L][l/L]|[i/I]) 



function_install


;;
 
[u/U][n/N][s/S][t/T][a/A][l/L][l/L]|[u/U])
function_uninstall
;;

*)
echo "dude u to unistall i to install"
exit
;;
esac

