#!/bin/bash -x

#Copyright (C) 2012 nowardev nowardev@gmail.com
 
#This file is part of kde-peace-settings.
 
#kde-peace-settings is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

PREFIX="/usr/local"
INSTALL=0

function usage() {
    echo "usage: $0 [i|u] [-p PREFIX]"
    echo
    echo "options:"
    echo "i    Install the package"
    echo "u    Uninstall the package"
    echo "p    Prefix to install to"
}

function_install(){
    for file in  "$PWD"/bin/* ; do
        install -m 755 -D $file "$PREFIX"/usr/bin/
    done

    for file in  "$PWD"/etc/X11/Xsession.d/* ; do
        install -m 644 "$file" "$PREFIX"/etc/X11/Xsession.d
    done 

    #mime 
    for file in  "$PWD"/usr/share/applications/* ; do 
        install -m 644 "$file" "$PREFIX"/usr/share/applications  
    done 

    #kde peace settings
    cp -r  "$PWD"/usr/share/kde-peace-settings  "$PREFIX"/usr/share/

    #kde peace doc 
    cp -r  "$PWD"/usr/share/doc/kde-peace-settings  "$PREFIX"/usr/share/doc/
}

function_uninstall(){
    rm -R  "$PREFIX"/usr/share/doc/kde-peace-settings
    rm -R  "$PREFIX"/usr/share/kde-peace-settings  
    rm "$PREFIX"/usr/share/applications/mimeapps.list
    rm "$PREFIX"/etc/X11/Xsession.d/50peace

    for file in "$PREFIX"/usr/bin/{ktexeditor-open-folder,lprinter-qt,lprinter-qt-office,vservice} ; do 
        rm "$file"
    done 
}

while getopts "p:iuh" OPTIONS; do
    case $OPTIONS in
        p)
            PREFIX=$OPTARG    
            ;;
        i)
            INSTALL=1
            ;;
        u)
            INSTALL=2
            ;;
        h)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ "$(id -u)" = 0 ]; then 
        echo "you have the power lol" 
        echo "installing..."
else 
        echo "YOU ARE NOT ROOT TO INSTALL  YOU MUST BE ROOT. "
        echo "have you typed wrong password?"
        exit 0
fi

if [[ "$INSTALL" == "1" ]]; then
    function_install
elif [[ "$INSTALL" == "2" ]]; then
    function_uninstall
else
    echo "Do you want install or unistall  (i\u)"
    read
    case $REPLY in
        [i/I][n/N][s/S][t/T][a/A][l/L][l/L]|[i/I]) 
            function_install
            ;;
        [u/U][n/N][s/S][t/T][a/A][l/L][l/L]|[u/U])
            function_uninstall
            ;;
        *)
            echo "dude u to unistall i to install"
            exit
            ;;
    esac
fi 
