#!/bin/bash 
#license gpl 
#copyright nowardev@gmail.com
version="0.0.1"
keyboard_default="us"

	program[0]="upnpc"
	program[1]="seren"
	for program in "${program[@]}";
	do if ! type -p "$program" >/dev/null;
	then echo "$program not found; PLEASE INSTALL IT" >&2
	tput setaf 1
	echo "error exiting..." >&2
	exit 1;
	fi; done


 
function_ask_name(){

username="$USER"
tput setaf 3
echo $"

Please Type a nickname, or press ENTER to set: $username"

read 

	if [[ -z "$REPLY" ]];then
		tput setaf 3
		echo $"No name selecting $USER"
		
	else
		tput setaf 3
		echo $"nickname:  $REPLY"
		username="$REPLY"
	fi


}

function_ask_keyboard(){



tput setaf 3
echo $"

Please select a keyboard layout, (us it es fr de): $keyboard_default"

read 

	if [[ -z "$REPLY" ]];then
		tput setaf 3
		echo $"No input given  selecting $keyboard_default"
		
	else
		tput setaf 3
		echo $"keyboard:  $REPLY"
		keyboard="$REPLY"
	fi
	
	loadkeys $keyboard

}

starter()
{

#CHECK PULSEAUDIO 
pulseactive="$(pidof pulseaudio)"
defaultdevice="00,00"

if [[ ! -z "$pulseactive" ]] ;then pulseactive="-d pulse";else  pulseactive=""; fi 


#get audio cards 
i=0
while read line ;do
IFS=- read -r  d m <<< "$line"; a="$d,$m" 
audiocard[$i]="plughw:$a"
i=$(($i+1))
done< <( grep capture /proc/asound/pcm | cut -d : -f 1)
if [[ ! -z "$pulseactive" ]] ;then audiocard[$i]="pulse"; defaultdevice="pulse"; fi 


#get name of audio cards 
i=0
while read line ;do
audionamecard[$i]="$line"
i=$(($i+1))
done< <(grep capture /proc/asound/pcm | cut -d : -f 2)
if [[ ! -z "$pulseactive" ]] ;then audionamecard[$i]="PULSEAUDIO (default)"; fi 


if [[ ${#audiocard[@]} >1 ]]; then 

echo $"
I have detected more than 1 microphone in your computer please select what you want to  use (0-$((${#audiocard[@]}-1)))
"

i=0
for (( i=0 ; i <${#audiocard[@]};i++)); do 
	tput setaf 2
	echo $"Choose $i for this Microphone:  ${audionamecard[$i]} "
done


read   

 
	if [[ "$REPLY" -ge "0" && "$REPLY" -lt "${#audiocard[@]}" ]];then
		tput setaf 5
		echo $"MicroPhone selected : device "${audionamecard["$REPLY"]}"  "${audiocard["$REPLY"]}""
		microphone="${audiocard["$REPLY"]}"
	else
		echo $"No Valid choice : setting microphone with $defaultdevice"
		microphone="$defaultdevice"
	fi
    
REPLY=""
else
microphone="${audiocard[0]}"
fi 

tput setaf 3
echo $"
upnpc -d 8110 UDP    &&  upnpc -a $( hostname -I) 8110 8110 UDP 

opening port 8110 now for your computer , wait a moment...
"
upnpc -d 8110 UDP >/dev/null    &&  upnpc -a $( hostname -I) 8110 8110 UDP >/dev/null  && tput setaf 2 &&  echo $"port 8110 is opened" 
tput setaf 7


 
tput setaf 5 ; echo "launching command : seren -n $username $pulseactive -D $microphone"; tput setaf 7 ; seren -n $username $pulseactive -D $microphone 

 

 
#closing port 
tput setaf 3
echo $"upnpc -d 8110 UDP : Closing port 8110...wait " && upnpc -d 8110 UDP >/dev/null 
tput setaf 2
echo $"port 8110 closed"


tput setaf 5
echo $"To run again seren type:

 serenstarter 

or directly:

 seren -n nickname
 
To change keyboard layout type"

tput setaf 7


}

function_ask_name
starter

#wget https://kde-peace-settings.googlecode.com/git/somescripts/serenpeace/serenstarter  -O $HOME/serenstarter ; chmod +x $HOME/serenstarter; sudo cp $HOME/serenstarter /usr/bin/serenstarter
