#!/bin/bash 
#license gpl 
#copyright nowardev@gmail.com
version="0.0.1"
keyboard_default="us"
hostname="$(hostname)"


tinykeyboard[0]="/usr/share/kmap/us.kmap" #default in tinycore
tinykeyboard[1]="/usr/share/kmap/qwerty/it-ibm.kmap"
tinykeyboard[2]="/usr/share/kmap/qwerty/es.kmap"
tinykeyboard[3]="/usr/share/kmap/azerty/fr.kmap"
tinykeyboard[4]="/usr/share/kmap/qwertz/de.kmap"

program[0]="upnpc"
program[1]="seren"
for program in "${program[@]}";
do if ! type -p "$program" >/dev/null;
then tput setaf 1 ;  echo "$program not found; PLEASE INSTALL IT" >&2
tput setaf 7
fi; done


 
function_ask_name(){

username="$USER"
tput setaf 6
echo $"

Please Type a nickname, or press ENTER to set: $username"
tput setaf 3
read 

	if [[ -z "$REPLY" ]];then
		tput setaf 3
		echo $"No name selecting $USER"
		
	else
		tput setaf 3
		echo $"nickname:  $REPLY"
		username="$REPLY"
	fi


}

function_ask_keyboard(){



tput setaf 6
echo $"

Please select a keyboard, (us it es fr de) or press ENTER to set: $keyboard_default"
tput setaf 3

case "$hostname" in 
tinyseren)

read 

	if [[ -z "$REPLY" ]];then
		tput setaf 3
		echo $"No input given  selecting $keyboard_default"
		keyboard="${tinykeyboard[0]}"
		
	else
		tput setaf 3
		echo $"keyboard:  $REPLY"
		case $REPLY in 
		us)
		keyboard="${tinykeyboard[0]}"
		;;
		it)
		keyboard="${tinykeyboard[1]}"
		;;
		es)
		keyboard="${tinykeyboard[2]}"
		;;
		fr)
		keyboard="${tinykeyboard[3]}"
		;;
		de)
		keyboard="${tinykeyboard[4]}"
		;;
		*)
		echo $"wrong name this script will only recognize us it es fr de for more layut edit this file : /opt/bootlocal.sh in the line loadkmap , remember to do filetool -b to save your settings!"
		keyboard="${tinykeyboard[0]}"
		;;
		esac
	fi
	
	sudo loadkmap < "$keyboard"


;;
debianseren)
read 

	if [[ -z "$REPLY" ]];then
		tput setaf 3
		echo $"No input given  selecting $keyboard_default"
		keyboard="$keyboard_default"
		
	else
		tput setaf 3
		echo $"keyboard:  $REPLY"
		keyboard="$REPLY"
	fi
	
	loadkeys $keyboard
;;
*)
echo 
;;
esac 
}

starter()
{

#CHECK PULSEAUDIO 
pulseactive="$(pidof pulseaudio)"
defaultdevice="00,00"

if [[ ! -z "$pulseactive" ]] ;then pulseactive="-d pulse";else  pulseactive=""; fi 


#get audio cards 
i=0
while read line ;do
IFS=- read -r  d m <<< "$line"; a="$d,$m" 
audiocard[$i]="plughw:$a"
i=$(($i+1))
done< <( grep capture /proc/asound/pcm | cut -d : -f 1)
if [[ ! -z "$pulseactive" ]] ;then audiocard[$i]="pulse"; defaultdevice="pulse"; fi 


#get name of audio cards 
i=0
while read line ;do
audionamecard[$i]="$line"
i=$(($i+1))
done< <(grep capture /proc/asound/pcm | cut -d : -f 2)
if [[ ! -z "$pulseactive" ]] ;then audionamecard[$i]="PULSEAUDIO (default)"; fi 


if [[ ${#audiocard[@]} >1 ]]; then 
tput setaf 6
echo $"
I have detected more than 1 microphone in your computer please select what you want to  use (0-$((${#audiocard[@]}-1)))
"

i=0
for (( i=0 ; i <${#audiocard[@]};i++)); do 
	echo $"Choose $i for this Microphone:  ${audionamecard[$i]} "
done


read   

 
	if [[ "$REPLY" -ge "0" && "$REPLY" -lt "${#audiocard[@]}" ]];then
		tput setaf 5
		echo $"MicroPhone selected : device "${audionamecard["$REPLY"]}"  "${audiocard["$REPLY"]}""
		microphone="${audiocard["$REPLY"]}"
	else
		echo $"No Valid choice : setting microphone with $defaultdevice"
		microphone="$defaultdevice"
	fi
    
REPLY=""
else
microphone="${audiocard[0]}"
fi 

if [[ "$(hostname)" != "tinyseren" ]] ; then 

	tput setaf 3
	echo -ne $"
upnpc -d 8110 UDP    &&  upnpc -a $( hostname -I) 8110 8110 UDP 

opening port 8110 now for your computer , wait a moment...
" && upnpc -d 8110 UDP >/dev/null    &&  upnpc -a $( hostname -I) 8110 8110 UDP >/dev/null  && tput setaf 2 &&  echo $"port 8110 is opened" 
	tput setaf 7
fi 

 
tput setaf 5 ; echo "launching command : seren -n $username $pulseactive -D $microphone"; tput setaf 7 ; seren -n $username $pulseactive -D $microphone 

 

 
#closing port 

if [[ "$(hostname)" == "tinyseren" ]] ; then 

	tput setaf 5
	echo $"

HOW CHANGE KEYBOARD LAYOUT:
#############################################
search in this location : /usr/share/kmap
there are many folders for example for italian
keyboard :

sudo loadkmap < /usr/share/kmap/qwerty/it-ibm.kmap

To make this permanent, add the command to /opt/bootlocal.sh (missing the sudo, since bootlocal is executed as root)
############################################"
else

	tput setaf 3
	echo -ne $"upnpc -d 8110 UDP : Closing port 8110...wait " && upnpc -d 8110 UDP >/dev/null 
	tput setaf 2 && echo $"port 8110 closed"


	tput setaf 5
	echo $"

HOW CHANGE KEYBOARD LAYOUT:

############################################
sudo dpkg-reconfigure console-data
sudo dpkg-reconfigure keyboard-configuration
sudo service keyboard restart
############################################
"
fi


tput setaf 5
echo $"
HOW START VOIP SEREN 

type in the terminal:

############
serenstarter
############

You can start seren also with:

#################
seren -n nickname 
#################"

tput setaf 7


}

if [[ "$hostname" == "debianseren" || "$hostname" == "tinyseren" ]]; then 
function_ask_keyboard
fi

function_ask_name
starter
